#!/usr/bin/env bash
#Install and setup load balancer
sudo apt-get -y update
sudo apt-get install -y haproxy
sudo sed -i "s/ENABLED=0/ENABLED=1/g" /etc/default/haproxy
sudo sed -i '$ a\ \nfrontend http_front\n\t bind *:80\n\tmode http\n\tdefault_backend http_back\n\nbackend http_back\n\tbalance roundrobin\n\tserver 458590-web-01 54.84.35.101 check\n\tserver 458590-web-02 3.85.1.133 check' /etc/haproxy/haproxy.cfg
sudo service haproxy start
