#!/usr/bin/env bash
#Bug server fixed
chmod 644 /etc/nginx/nginx.conf
sed -Ei 's/\s*#?\s*user nginx;/' /etc/nginx/nginx.conf
sed -E 's/(listen (\[::\]:)?80) /\180 /' etc/nginx/sites-enabled/default
pkill apache2
# restart
su ngix -s /bin/bash -c 'service nginx restart'
